name: Publish

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: primer/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}  
